### ISSUE TITLE
HTML contents overflow the output area

### ISSUE THREAD

**Issue by munierujp** [munierujp/md2html#3]
## Example
<img width="1072" alt="2018-05-09 23 25 27" src="https://user-images.githubusercontent.com/20086673/39820465-d71eb982-53e0-11e8-999f-9ba1fbc3d336.png">

## FYI
```css
#main {
  display: flex;
  overflow-wrap: break-word;
}

#output {
  flex: 1;
  min-width: 0;
}
```
